#!/usr/bin/env lua

if arg[1]==nil or arg[1]=="-h" or arg[1]=="-help" or arg[1]=="--help" then
	print(arg[0]..[[ -- Autogenerates loaders for ObjL libraries in C
Usage:
	]]..arg[0].." libname")
	os.exit()
end

io.write([[#!/usr/bin/env lua

--[[ObjL (Objective Lua) library loading code autogenerated by autogen_loader.lua (part of the ObjL package)
ObjL is (c) 2006 John Ohno and is licensed under the GNU LGPL.

The file used to generate this code may be found in the tools/ directory of your copy of ObjL.

This file REQUIRES ObjL. If you do not have it, you may obtain it here: 
	http://luaforge.net/projects/objl

Please post all bug reports for ObjL apps (including this autogenerated file) to the above site.
--]]

require("ObjL")

]]..arg[1]..[[=loadlib("]]..arg[1]..[[")

function ]]..arg[1]..[[:___new(o)
	o=o or {}
	self.obj=init(unpack(o))
	for i,v in pairs(super) do
		if type(v)=="function" then
			self[i]=function(...)
				v(self.obj, arg)
			end
		end
	end
end

class=class or ObjLua.class

for i,v in pairs(]]..arg[1]..[[) do
	if type(v)=="table" then
		v:___new=]]..arg[1]..[[:___new
		v:init=v:init or v:new
		v=class(v)
	end
end

]]..arg[1]..[[=class(]]..arg[1]..[[)

return ]]..arg[1].."\n")


